[package]
name = "trivia_project"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.6"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
html-escape = "0.2"
rand = "0.8"

